name: Build and Test C Project

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3
      with:
        repository: codefresh-contrib/c-sample-app
        ref: master

    - name: Set up GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile sources
      run: make

    - name: Run tests
      run: make test

        # Create a new tag based on the commit SHA

    - uses: actions/checkout@v2
    - name: Create Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        TAG_NAME="v$(date +'%Y.%m.%d.%H%M%S')"  # Tag format: vYYYY.MM.DD.HHMMSS
        echo "Generated tag: $TAG_NAME"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag $TAG_NAME
        git push origin $TAG_NAME

      # Create GitHub Release

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: $TAG_NAME
        release_name: Release $TAG_NAME
        body: |
          Release created automatically by GitHub Actions.
        draft: false
