name: Parallel Pipelines

on:
  push:
    branches:
      - main

jobs:
  pipeline_one:
    name: Pipeline One
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Pipeline One Tasks
        run: |
          echo "Running tasks for Pipeline One"
          # Add your commands here
          sleep 10

  pipeline_two:
    name: Pipeline Two
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Pipeline Two Tasks
        run: |
          echo "Running tasks for Pipeline Two"
          # Add your commands here
          sleep 10
