name: deploy

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Add Tag to deploy'
        required: true

jobs:
  release-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Release artifact
        uses: robinraju/release-downloader@v1.8
        env:
          TAG: ${{ github.event.inputs.TAG }}
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.inputs.TAG }}
          fileName: my-app.zip
          out-file-path: ./deployment
          token: ${{ secrets.GITHUB_TOKEN }}
