name: deploy

on:
  push:
    branches:
      - release  
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Add Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Release artifact
        uses: robinraju/release-downloader@v1.8
        env:
          ENVIRONMENT: ${{ github.event.inputs.TAG }}
        with:
          repository: ${{ github.repository }}
          tag: $TAG
          fileName: my-app.zip
          out-file-path: ./deployment
