name: deploy

on:
  push:
    branches:
      - release  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact from triggered workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          name: my-app.zip
          repo: ${{ github.repository }}
          path: ./artifacts
          search_artifacts: true
