name: deploy

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Add Tag to deploy'
        required: true

jobs:
  release-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Release artifact
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.inputs.TAG }}
          fileName: my-app.zip
          out-file-path: ./deployment

      - name: Unzip Artifact
        run: |
          unzip ./deployment/my-app.zip -d ./app

      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
           ls -al 


